# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

message_key: "\xF6v\vQ\xA46S\xA8\xDCr*tM\xE9or" #add to user's passwords
# message_key_32: "\x86\xDD\xAC\x1F,\xF7W[5\xD2\x1C\xA7O\xBA\xBB9/y\xD2\xAFf\x91\e\xC1?\xD4\x13\xF1\ar@?"
message_key_32: "\xA3\xFC[I6\xD9\xE9\x877\xE1\x9D\xA3L\xD4\xE4\xFF\xD6\xD6E0Gp\x97&\xEA\x95\xEFmSH]Q"
# message_key_32: "I/bK6YJGnRIGJL+lHnYvwAFtq5kSeWFGsYZLMsXm8gs="
# message_key_32: "OEPA3Fa3sheDmRacjb+N7P9noD11YW27bZynVkdJKZM="
algorithm: "AES-256-CBC"
RAILS_GA_CODE: UA-96863281-1